### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ronnievisser** [frankkessler/salesforce-laravel-oauth2-rest#31]
Hi,

When installing this package the following error occurs:

Problem 1
    - frankkessler/salesforce-laravel-oauth2-rest v0.4.5 requires frankkessler/guzzle-oauth2-plugin dev-master -> no matching package found.
    - frankkessler/salesforce-laravel-oauth2-rest v0.4.4 requires frankkessler/guzzle-oauth2-plugin dev-master -> no matching package found.
    - frankkessler/salesforce-laravel-oauth2-rest v0.4.0.3 requires frankkessler/guzzle-oauth2-plugin dev-master -> no matching package found.
    - frankkessler/salesforce-laravel-oauth2-rest v0.4.0.2 requires frankkessler/guzzle-oauth2-plugin dev-master -> no matching package found.
    - frankkessler/salesforce-laravel-oauth2-rest v0.4.0.1 requires frankkessler/guzzle-oauth2-plugin dev-master -> no matching package found.
    - frankkessler/salesforce-laravel-oauth2-rest v0.4.0 requires frankkessler/guzzle-oauth2-plugin dev-master -> no matching package found.
    - Installation request for frankkessler/salesforce-laravel-oauth2-rest 0.4.* -> satisfiable by frankkessler/salesforce-laravel-oauth2-rest[v0.4.0, v0.4.0.1, v0.4.0.2, v0.4.0.3, v0.4.4, v0.4.5].

**Comment by frankkessler** [comment]
This package was relying on a repository.  I've changed the dependency to be a packagist package so as of v0.4.7, this error shouldn't appear anymore
