### ISSUE TITLE
Bulk API query

### ISSUE THREAD

**Issue by ronnievisser** [frankkessler/salesforce-laravel-oauth2-rest#33]
Hi,

Am I correct that running a query via the bulk API is not yet supported in this package?

**Comment by frankkessler** [comment]
v0.4.8 should handle bulk querying correctly

**Comment by ronnievisser** [comment]
according to documentation we have to check $result->success but this throws and undefined property exception. probably because it extends the BaseReponse instead of the SalesforceBaseResponse class.

**Comment by frankkessler** [comment]
I just changed the examples to use $result->id instead.  The bulk api doesn't return a success variable like the regular sobject api does for most requests.  So I'm going to leave it out for now.
