### ISSUE TITLE
custom rest services

### ISSUE THREAD

**Issue by ronnievisser** [frankkessler/salesforce-laravel-oauth2-rest#38]
Hi,

It would be very helpful if we could use this package also with custom rest services.

is this something you are going to add?

thanks

**Comment by frankkessler** [comment]
They are supported.  I'll add an example later, but it's something like $salesforce->custom()->get('servicename');

**Comment by ronnievisser** [comment]
A that's nice!

**Comment by ronnievisser** [comment]
BTW, any ideas of supporting chatter uploads? for API 36.0+ and older? (from 36.0 uploads and message creation should be separated).

thanks

**Comment by frankkessler** [comment]
There's a raw request for GET and POST in the Salesforce.php file that you can use for anything not covered by the current api.  I don't have any plans to add it at this time.
