### ISSUE TITLE
invalid session id

### ISSUE THREAD

**Issue by ronnievisser** [frankkessler/salesforce-laravel-oauth2-rest#39]
Hi,

After a few hours of issuing an access token I get a invalid session id response back from Salesforce. to I need to refresh the token manually? 

In my opinion and looking at the code it should refresh automatically, right?

**Comment by frankkessler** [comment]
Is the refresh token definitely available in your database or in the constructor?

**Comment by ronnievisser** [comment]
problem was with the instance url returned by SFDC. it also had https:// in it and I see that in the code also add https://. so I removed 1 and now it seems to work properly.

**Comment by kishan93** [comment]
Bulk Job gives me the same erorr. (invalidSessionId)
