### ISSUE TITLE
Can we use it for chatter posts?

### ISSUE THREAD

**Issue by ronnievisser** [frankkessler/salesforce-laravel-oauth2-rest#43]
Hi,

I'm trying to fixture our if we are able to use this package for chatter uploads.

do you have any information about this?

Thank you!

**Comment by frankkessler** [comment]
There's a raw request for GET and POST in the Salesforce.php file that you can use for anything not covered by the current api. I don't have any plans to add it at this time.

You could do something like this:  $me = Salesforce::rawGetRequest('chatter/users/me');  This should send a GET request to https://instance.salesforce.com/services/data/v36.0/chatter/users/me
