### ISSUE TITLE
Advice for large datasets

### ISSUE THREAD

**Issue by ronnievisser** [frankkessler/salesforce-laravel-oauth2-rest#45]
Hi,

I have to update large datasets in Salesforce. let's say about 100000 records. using the runBatch structure this consumes a lots of memory.

currently i'm using all the methods separate and use the laravel chunk option to add batches to the job. this works perfect and keep the memory as low as possible.

The only thing i'm missing not is the response. DO you have any best practices on how to get these? or should I just copy some code from the runBatch method?

thnx

**Comment by frankkessler** [comment]
I would take what's in the runBatch function to get you started.  It sounds like you'll want to run each batch result separately as well to conserve memory.  You might want to store the batch ids in a database or queue and then poll each of them every few minutes to see if they are complete so you can process the results.  

Some of the code in the runBatch function tries to put all of the results back into the $job object.  That's definitely going to run up your memory so I would avoid that.
