### ISSUE TITLE
allow for Sforce-Enable-PKChunking

### ISSUE THREAD

**Issue by ronnievisser** [frankkessler/salesforce-laravel-oauth2-rest#53]
Hi,

Would it be possible to allow for PK chunking when querying the bulk API?
Sforce-Enable-PKChunking: chunkSize=250000;

current I have to process about 600000 records which is consuming all my memory since it only used 1 batch to get the data.

thanks

**Comment by frankkessler** [comment]
Added in release v0.4.14
